### ISSUE TITLE
[오픈소스 사용]

### ISSUE THREAD

**Issue by 12302a** [samsunghappytree123/discord-Promotion-Bot#23]
## 디스코드 정보를 기재해주세요.
+ 디스코드 닉네임#태그 (Discord#0000) :  12302a#5252
+ 디스코드 ID (123456789) :  654245768055619584

## 오픈소스를 사용하며 라이센스를 지킬 수 있으신가요?
예

**Comment by samsunghappytree123** [comment]
확인했습니다 :)
