### ISSUE TITLE
[버그]

### ISSUE THREAD

**Issue by 12302a** [samsunghappytree123/discord-Promotion-Bot#24]
## 어떤 버그인가요?
> 채널 업로드 과정중 오류

## 개발 환경은 어떠신가요?
> 
python 3.9.6
discord            2.1.0
discord.py         1.6.0

## 오류 코드가 무엇인가요?
> AttributeError: 'NoneType' object has no attribute 'send'

## 구글링을 해보셨나요?
+ [x] 네 구글링 해보았습니다.

**Comment by samsunghappytree123** [comment]
1. target_category가 None이 아닌지 확인 부탁드립니다.
2. discord와 discord.py의 버전을 하나로 통일해주시기 바랍니다.

**Comment by samsunghappytree123** [comment]
1. discord.py 1.7.3 버전으로 시도하셨나요?

**Comment by samsunghappytree123** [comment]
내일 확인해보겠습니다

**Comment by 12302a** [comment]
계신가요

**Comment by 12302a** [comment]
File "/Users/Library/Python/3.9/lib/python/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/Users/hanseung/Promotion/index.py", line 268, in on_message
    for a in target_category.channels:
AttributeError: 'NoneType' object has no attribute 'channels'

가 지속적으로 표시되네요 등록 처리안되고

**Comment by samsunghappytree123** [comment]
새로운 index.py 파일 다시 다운받으시면 될 것 같습니다.

**Comment by samsunghappytree123** [comment]
수정 내용 : https://github.com/samsunghappytree123/discord-Promotion-Bot/commit/fa02611493d45ab0c639442286275c2d03e551a2

**Comment by 12302a** [comment]
넵 알겠습니다
